
-- CREACIÓN DE BASE DE DATOS DE ECOLONIA — MySQL
-- OSCAR EDUARDO CISNEROS LARIOS -  MIERCOLES 2 DE OCTUBRE 2013

DROP SCHEMA IF EXISTS eColonia;
CREATE DATABASE IF NOT EXISTS eColonia;
USE eColonia;

DROP TABLE IF EXISTS Colonia;

DROP TABLE IF EXISTS CatalogoCalle;
CREATE TABLE CatalogoCalle (
	Id INT NOT NULL AUTO_INCREMENT,
	Nombre VARCHAR(20) NOT NULL,
	Colonia INT NOT NULL CHECK (Colonia > 0),
	CONSTRAINT PK_CatalogoCalle PRIMARY KEY (Id)
);

DROP TABLE IF EXISTS Casa;
CREATE TABLE Casa (
	Id INT NOT NULL AUTO_INCREMENT,
	Calle INT NOT NULL CHECK (Calle > 0 ),
	Colonia INT NOT NULL CHECK (Colonia > 0),
	Familia VARCHAR(50) NOT NULL,
	-- Familia es un atributo calculado del nombre de la padre y madre de la casa
	Numero INT NOT NULL,
	Te_Casa VARCHAR(30) NOT NULL,
	CONSTRAINT PK_Casa PRIMARY KEY (Id),
	CONSTRAINT FK_Calle FOREIGN KEY (Calle) REFERENCES CatalogoCalle (Id) ON DELETE NO ACTION ON UPDATE CASCADE
);

-- Darles nombres a los atributos (CONSTRAINT)
-- Vista: Colonos por ocupación
	
DROP TABLE IF EXISTS CatalogoOcupaciones;
CREATE TABLE CatalogoOcupaciones (
	Id INT NOT NULL AUTO_INCREMENT,
	Nombre VARCHAR(40) NOT NULL,
	CONSTRAINT PK_CatalogoOcupaciones PRIMARY KEY (Id)
);

DROP TABLE IF EXISTS Colono;
CREATE TABLE Colono (
	Id INT NOT NULL AUTO_INCREMENT,
	Casa INT NOT NULL CHECK (Casa > 0),
	Calle INT NOT NULL CHECK (Calle > 0),
	ApellidoPaterno VARCHAR(30) NOT NULL,
	ApellidoMaterno VARCHAR(30) NOT NULL,
	FechaNacimiento DATETIME NOT NULL,
	Estatura REAL NOT NULL,
	Genero CHAR(1) NOT NULL DEFAULT 'F' CHECK (Genero IN ('M', 'F')),
	Nombre VARCHAR(30) NOT NULL, 
	RolFamiliar CHAR(1) NOT NULL CHECK (RolFamiliar IN ('P', 'M')),
	Ocupacion INT NOT NULL CHECK (Ocupacion > 0), 
	Peso FLOAT NOT NULL DEFAULT '0',
	Email VARCHAR(50) NOT NULL,
	Sexo CHAR(1) NOT NULL CHECK (Sexo IN ('M', 'F')),
	Tel_celular VARCHAR(12) NOT NULL DEFAULT '000-00-00000' CHECK (Telefono LIKE '[0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9][0-9][0-9][0-9]'),
	CONSTRAINT PK_Colono PRIMARY KEY (Id),
	CONSTRAINT FK_Colono_Casa FOREIGN KEY (Casa) REFERENCES Casa (Id) ON DELETE NO ACTION ON UPDATE CASCADE,
	CONSTRAINT FK_Colono_Calle FOREIGN KEY (Calle) REFERENCES CatalogoCalle (Id) ON DELETE NO ACTION ON UPDATE CASCADE,
	CONSTRAINT FK_Colono_Ocupacion FOREIGN KEY (Ocupacion) REFERENCES CatalogoOcupaciones (Id) ON DELETE NO ACTION ON UPDATE CASCADE
);

DROP TABLE IF EXISTS ComiteDeBarrio;
CREATE TABLE ComiteDeBarrio (
	Id INT NOT NULL AUTO_INCREMENT,
	Colonia INT NOT NULL CHECK (Colonia > 0),
	FI DATETIME NOT NULL,
	FF DATETIME NOT NULL,
	Nombre VARCHAR(30) NOT NULL,
	Numero_Integrantes INT NOT NULL DEFAULT 0 CHECK (Numero_Integrantes > 0 AND Numero_Integrantes < 20),
	Presidente INT NOT NULL CHECK (Presidente > 0),
	CONSTRAINT PK_ComiteDeBarrio PRIMARY KEY (Id),
	CONSTRAINT FK_ComiteDeBarrio_Presidente FOREIGN KEY (Presidente) REFERENCES Colono (Id) ON DELETE No ACTION ON UPDATE CASCADE
);

DROP TABLE IF EXISTS CatalogoDependencias;
CREATE TABLE CatalogoDependencias (
	Id INT NOT NULL AUTO_INCREMENT,
	Nombre VARCHAR(30) NOT NULL,
	CONSTRAINT PK_CatalogoDependencias PRIMARY KEY (Id)
);

DROP TABLE IF EXISTS Estado;
CREATE TABLE Estado (
	Id INT NOT NULL AUTO_INCREMENT,
	Nombre VARCHAR(30) NOT NULL DEFAULT 'NombreEstado',
	CONSTRAINT PK_Estado PRIMARY KEY (Id)
);

DROP TABLE IF EXISTS Municipio;
CREATE TABLE Municipio(
	Id INT NOT NULL AUTO_INCREMENT,
	Estado INT NOT NULL CHECK (Estado > 0),
	Nombre VARCHAR(30) NOT NULL,
	Email VARCHAR(30) NOT NULL,
	CONSTRAINT PK_Municipio PRIMARY KEY (Id),
	CONSTRAINT FK_Municipio_Estado FOREIGN KEY (Estado) REFERENCES Estado (Id) ON DELETE NO ACTION ON UPDATE CASCADE	
);

CREATE TABLE Colonia (
	Id INT NOT NULL AUTO_INCREMENT,
	Municipio INT NOT NULL CHECK (Municipio > 0),
	ComiteDeBarrio INT NOT NULL CHECK (ComiteDeBarrio > 0),
	FechaFun DATETIME NOT NULL,
	NumeroHabitantes INT NOT NULL DEFAULT 0,
	Nombre VARCHAR(30) NOT NULL DEFAULT 'Nombre',
	Ubicacion VARCHAR(100) NOT NULL DEFAULT 'Ubicacion',
	Diagnostico_inicial TEXT NOT NULL,
	Extension_Geografica VARCHAR(20) NOT NULL,
	Croquis TEXT NOT NULL,
	CONSTRAINT PK_Colonia PRIMARY KEY (Id),
	CONSTRAINT FK_Colonia_Municipio FOREIGN KEY (Municipio) REFERENCES Municipio (Id) ON DELETE NO ACTION ON UPDATE CASCADE,
	CONSTRAINT FK_Colonia_ComiteDeBarrio FOREIGN KEY (ComiteDeBarrio) REFERENCES ComiteDeBarrio (Id) ON DELETE NO ACTION ON UPDATE CASCADE
);

ALTER TABLE ComiteDeBarrio ADD CONSTRAINT FK_ComiteDeBarrio_Colonia FOREIGN KEY (Colonia) REFERENCES Colonia (Id) ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE CatalogoCalle ADD CONSTRAINT FK_CatalogoCalle_Colonia FOREIGN KEY (Colonia) REFERENCES Colonia (Id) ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE Casa ADD CONSTRAINT FK_Casa_Colonia FOREIGN KEY (Colonia) REFERENCES Colonia (Id) ON DELETE NO ACTION ON UPDATE CASCADE;

DROP TABLE IF EXISTS Autoridad;
CREATE TABLE Autoridad (
	Id INT NOT NULL AUTO_INCREMENT,
	Nombre VARCHAR(20) NOT NULL,
	ApellidoP VARCHAR(30) NOT NULL,
	ApellidoM VARCHAR(30) NOT NULL,
	Correo VARCHAR(50) NOT NULL,
	CONSTRAINT PK_Autoridad PRIMARY KEY (Id)
);

DROP TABLE IF EXISTS Autoridad_Dependencia;
CREATE TABLE Autoridad_Dependencia (
	Id INT NOT NULL AUTO_INCREMENT,
	Autoridad INT NOT NULL CHECK (Autoridad > 0),
	Dependencia INT NOT NULL CHECK (Dependencia > 0),
	InicioPeriodo DATETIME NOT NULL,
	FinPeriodo DATETIME NOT NULL,
	Municipio INT NOT NULL CHECK (Municipio > 0),
	Puesto VARCHAR(30) NOT NULL,
	CONSTRAINT PK_Autoridad_Dependencia PRIMARY KEY (Id),
	CONSTRAINT FK_Autoridad_Dependencia_Autoridad FOREIGN KEY (Autoridad) REFERENCES Autoridad (Id) ON DELETE NO ACTION ON UPDATE CASCADE,
	CONSTRAINT FK_Autoridad_Dependencia_Dependencia FOREIGN KEY (Dependencia)  REFERENCES CatalogoDependencias (Id) ON DELETE NO ACTION ON UPDATE CASCADE
);

